name: Clean Cache
description: Cleans up caches for GitHub Actions based on branch or PR ref
author: Opengrabeso
branding:
  icon: trash
  color: green
runs:
  using: node20
  main: 'dist/index.js'
  post: 'dist/post.js'
inputs:
  token:
    required: true
    description: Authenticated GitHub token.
    default: '${{ github.token }}'
  ref:
    required: false
    description: The full Git reference for which the cache should be cleaned. Use refs/pull/<number>/merge for PRs.
    default: 'refs/heads/${{ github.ref_name }}'
  except:
    description: Key which should not be deleted
  post:
    description: Run the cleanup post workflow
    default: 'false'
  keep:
    description: Number of most recent items to keep
    default: '0'
